services:
  churn-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-app
    ports:
      - "8505:8501"
    restart: unless-stopped
    networks:
      - churn-net

networks:
  churn-net:
    driver: bridge
